#!/bin/sh

ENABLED=yes
PROCS=dnscrypt-proxy
ARGS="--local-address=0.0.0.0:65053 --daemonize -R dnscrypt.eu-dk"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
