#!/bin/sh
# The AsusWRT-Merlin services start.
# This script will be executed upon bootup.

/jffs/scripts/entware-start.sh

/jffs/scripts/iptables-setup.sh

# cru a serv '8,18,28,38,48,58 * * * * /jffs/scripts/cron.sh'
cru a serv '* * * * * /jffs/scripts/cron.sh'
